version: '3.8'

services:
  web-service:
#    build: .
    image: bolshov92/construction_company_management-web-service:v1.0
    volumes:
      - /host/path:/container/path:ro
    container_name: company_management
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - company_network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Bolshov92
      MYSQL_DATABASE: company_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - company_network

volumes:
  mysql_data:
    driver_opts:
      type: none
      o: bind
      device: /path/to/mysql_data

networks:
  company_network:
    driver: bridge