spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/company_management
    username: root
    password: Bolshov92

jpa:
  hibernate:
    ddl-auto: none

    sql:
      init:
        data-location:
          classpath: db/data.sql
        schema-locations: classpath:db/schema.sql
        mode: always
