spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:company_management}?allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:Bolshov92}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    root: INFO
    com.example.construction_company_management: DEBUG
  file:
    name: construction_company_management.log

#server:
#  port: 8090