spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/company_management
    username: root
    password: Bolshov92

  jpa:
   hibernate:
    ddl-auto: update

  sql:
   init:
    schema-locations: classpath:db/schema.sql
    mode: always
    data-locations: classpath:db/data.sql

server:
  port: 8081
