spring:
  main:
    banner-mode: off

    datasource:
      url: jdbc:mysql://localhost:3306/construction_company_management
      username: root
      password: file://~/Home/IT/pass.txt

      jpa:
        hibernate:
          ddl-auto: update
          database: mysql
          show-sql: true
          properties:
            hibernate:
              format_sql: true