spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company_management
    username: root
    password: Bolshov92
    driver-class-name: com.mysql.cj.jdbc.Driver

    initialization-mode : always
    schema:  classpath:schema.sql